### ISSUE TITLE
build ld error

### ISSUE THREAD

**Issue by kay54068** [OneMoreGres/qtc-utilities#1]
@OneMoreGres 
Thank you share the great plugin, I want try build the project but get some error about this:

![圖片](https://user-images.githubusercontent.com/3054544/92503096-531ec200-f233-11ea-9702-84c30089e39f.png)

how can i fixed it ?

BR,
thanks

**Comment by OneMoreGres** [comment]
Have you adjusted `paths.pri` file? `QTCREATOR_SOURCES` and  `IDE_BUILD_TREE` must point to the proper sources and built Qt Creator locations.
Also take a look at CI build scripts at `util/ci`

**Comment by kay54068** [comment]
Hi @OneMoreGres ,

Thanks your reply , I confirm the paths.pri and change the  IDE_BUILD_TREE  Path after build success.

btw,
do you know how can define the ".so" file install Path  when build success?


BR,
thanks

**Comment by OneMoreGres** [comment]
So now you can successfully build the plugin?

`USE_USER_DESTDIR` somehow affects resulting "*.so" location (its usage is in `qtcreator-src/src/qtcreatorplugin.pri`). But I have never used it.

**Comment by kay54068** [comment]
> So now you can successfully build the plugin?
> 
> `USE_USER_DESTDIR` somehow affects resulting "*.so" location (its usage is in `qtcreator-src/src/qtcreatorplugin.pri`). But I have never used it.

Thanks your reply ,

I can successfully build the qtc-utilities plugin.
I confirm that the USE_USER_DESTDIR config seems to be installed in the default path.


Thank you very much for your help 😄
